/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest;

import java.util.HashMap;
import java.util.Map;

import ke.co.credofaster.partner.apitest.models.*;

public class Configuration {
    //Assigned APIKey
    //TODO: Replace the apiKey with an appropriate value
    public static String apiKey = "XXXX-XXXX-XXXX-XXXX";

    //Assigned ClientId
    //TODO: Replace the clientId with an appropriate value
    public static String clientId = "ABCDEDFG1234";

    /**
     * Current API environment
     */
    public static Environments environment = Environments.SANDBOX;

    /**
     * Get base URI by current environment
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public static String getBaseUri(Servers server) {
        StringBuilder baseUrl = new StringBuilder(environmentMapper(Configuration.environment, server));
        Map<String, Object> parameters = new HashMap<String, Object>();
        APIHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }
    
    /**
     * Get base URI by current environment
     * @return Processed base URI
     */
    public static String getBaseUri() {
        return Configuration.getBaseUri(Servers.ENUM_DEFAULT);
    }
    
    /**
     * Base URLs by environments and server aliases 
     */

    private static String environmentMapper(Environments environments, Servers servers) {
		String url = "";
		if(environments.equals(Environments.PRODUCTION)) {
			if(servers.equals(Servers.ENUM_DEFAULT))
				url = "https://api.partner.credofaster.co.ke";
			if(servers.equals(Servers.MY_CALLBACK_ENDPOINT))
				url = "https://posthere.io/dfd0-4d32-8ad9";
		}
		if(environments.equals(Environments.SANDBOX)) {
			if(servers.equals(Servers.ENUM_DEFAULT))
				url = "https://api-test.partner.credofaster.co.ke";
			if(servers.equals(Servers.MY_CALLBACK_ENDPOINT))
				url = "https://posthere.io/dfd0-4d32-8ad9";
		}
		if(environments.equals(Environments.DEVELOPMENT)) {
			if(servers.equals(Servers.ENUM_DEFAULT))
				url = "https://partner.credofaster.co.ke/crm_api/api/";
			if(servers.equals(Servers.MY_CALLBACK_ENDPOINT))
				url = "https://partner.credofaster.co.ke/crm_api/api/";
		}
		return url;
	}
}
