/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class DenominationBuilder {
    //the instance to build
    private Denomination denomination;

    /**
     * Default constructor to initialize the instance
     */
    public DenominationBuilder() {
        denomination = new Denomination();
    }

    /**
     * Available Name: KE
     */
    public DenominationBuilder name(String name) {
        denomination.setName(name);
        return this;
    }

    /**
     * Amount to Request
     */
    public DenominationBuilder value(int value) {
        denomination.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Denomination build() {
        return denomination;
    }
}