/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Denomination 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4348038076294680248L;
    private String name = "KE";
    private int value = 10;
    /** GETTER
     * Available Name: KE
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Available Name: KE
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Amount to Request
     */
    @JsonGetter("value")
    public int getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * Amount to Request
     */
    @JsonSetter("value")
    public void setValue (int value) { 
        this.value = value;
    }
 
}
