/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class EventCallbackFeedbackBuilder {
    //the instance to build
    private EventCallbackFeedback eventCallbackFeedback;

    /**
     * Default constructor to initialize the instance
     */
    public EventCallbackFeedbackBuilder() {
        eventCallbackFeedback = new EventCallbackFeedback();
    }

    public EventCallbackFeedbackBuilder errorCode(int errorCode) {
        eventCallbackFeedback.setErrorCode(errorCode);
        return this;
    }

    public EventCallbackFeedbackBuilder errorDescription(String errorDescription) {
        eventCallbackFeedback.setErrorDescription(errorDescription);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EventCallbackFeedback build() {
        return eventCallbackFeedback;
    }
}