/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class EventCallbackPayloadBuilder {
    //the instance to build
    private EventCallbackPayload eventCallbackPayload;

    /**
     * Default constructor to initialize the instance
     */
    public EventCallbackPayloadBuilder() {
        eventCallbackPayload = new EventCallbackPayload();
    }

    /**
     * This is shared by the system and should be referred when doing any debugging
     */
    public EventCallbackPayloadBuilder eventId(String eventId) {
        eventCallbackPayload.setEventId(eventId);
        return this;
    }

    /**
     * Contains the EVENT type.  detailed list of this can be shared on Request to the admin
     */
    public EventCallbackPayloadBuilder eventType(String eventType) {
        eventCallbackPayload.setEventType(eventType);
        return this;
    }

    /**
     * For Events that are related with the Clients Request, you will get a Request ID that was generate by the system when you made a  service call
     */
    public EventCallbackPayloadBuilder requestId(String requestId) {
        eventCallbackPayload.setRequestId(requestId);
        return this;
    }

    /**
     * Contains any addition fields,(CAN BE NESTED). See the PDF for more details
     */
    public EventCallbackPayloadBuilder eventData(Object eventData) {
        eventCallbackPayload.setEventData(eventData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EventCallbackPayload build() {
        return eventCallbackPayload;
    }
}