/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class EventCallbackPayload 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8906439927771726891L;
    private String eventId = "123456789";
    private String eventType = "QUEUED";
    private String requestId;
    private Object eventData;
    /** GETTER
     * This is shared by the system and should be referred when doing any debugging
     */
    @JsonGetter("EventId")
    public String getEventId ( ) { 
        return this.eventId;
    }
    
    /** SETTER
     * This is shared by the system and should be referred when doing any debugging
     */
    @JsonSetter("EventId")
    public void setEventId (String value) { 
        this.eventId = value;
    }
 
    /** GETTER
     * Contains the EVENT type.  detailed list of this can be shared on Request to the admin
     */
    @JsonGetter("EventType")
    public String getEventType ( ) { 
        return this.eventType;
    }
    
    /** SETTER
     * Contains the EVENT type.  detailed list of this can be shared on Request to the admin
     */
    @JsonSetter("EventType")
    public void setEventType (String value) { 
        this.eventType = value;
    }
 
    /** GETTER
     * For Events that are related with the Clients Request, you will get a Request ID that was generate by the system when you made a  service call
     */
    @JsonGetter("RequestId")
    public String getRequestId ( ) { 
        return this.requestId;
    }
    
    /** SETTER
     * For Events that are related with the Clients Request, you will get a Request ID that was generate by the system when you made a  service call
     */
    @JsonSetter("RequestId")
    public void setRequestId (String value) { 
        this.requestId = value;
    }
 
    /** GETTER
     * Contains any addition fields,(CAN BE NESTED). See the PDF for more details
     */
    @JsonGetter("EventData")
    public Object getEventData ( ) { 
        return this.eventData;
    }
    
    /** SETTER
     * Contains any addition fields,(CAN BE NESTED). See the PDF for more details
     */
    @JsonSetter("EventData")
    public void setEventData (Object value) { 
        this.eventData = value;
    }
 
}
