/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class InitiatorBuilder {
    //the instance to build
    private Initiator initiator;

    /**
     * Default constructor to initialize the instance
     */
    public InitiatorBuilder() {
        initiator = new Initiator();
    }

    /**
     * Client Type Initiating the Request
     */
    public InitiatorBuilder type(String type) {
        initiator.setType(type);
        return this;
    }

    /**
     * Client ID Initiating the Request
     */
    public InitiatorBuilder id(String id) {
        initiator.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Initiator build() {
        return initiator;
    }
}