/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Initiator 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5866898405079617819L;
    private String type = "PARTNER";
    private String id = "10001";
    /** GETTER
     * Client Type Initiating the Request
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Client Type Initiating the Request
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * Client ID Initiating the Request
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Client ID Initiating the Request
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
}
