/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PartnerAirtimeRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3601284930676197530L;
    private Initiator initiator;
    private List<SingleAirtimeParameter> parameters;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("initiator")
    public Initiator getInitiator ( ) { 
        return this.initiator;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("initiator")
    public void setInitiator (Initiator value) { 
        this.initiator = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parameters")
    public List<SingleAirtimeParameter> getParameters ( ) { 
        return this.parameters;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parameters")
    public void setParameters (List<SingleAirtimeParameter> value) { 
        this.parameters = value;
    }
 
}
