/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class PartnerAirtimeRequestBuilder {
    //the instance to build
    private PartnerAirtimeRequest partnerAirtimeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public PartnerAirtimeRequestBuilder() {
        partnerAirtimeRequest = new PartnerAirtimeRequest();
    }

    public PartnerAirtimeRequestBuilder initiator(Initiator initiator) {
        partnerAirtimeRequest.setInitiator(initiator);
        return this;
    }

    public PartnerAirtimeRequestBuilder parameters(List<SingleAirtimeParameter> parameters) {
        partnerAirtimeRequest.setParameters(parameters);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PartnerAirtimeRequest build() {
        return partnerAirtimeRequest;
    }
}