/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PartnerAirtimeResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1050836276907476683L;
    private int errorCode = 0;
    private String errorDescription;
    private UUID referenceId;
    private UUID requestId;
    /** GETTER
     * Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
     */
    @JsonGetter("ErrorCode")
    public int getErrorCode ( ) { 
        return this.errorCode;
    }
    
    /** SETTER
     * Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
     */
    @JsonSetter("ErrorCode")
    public void setErrorCode (int value) { 
        this.errorCode = value;
    }
 
    /** GETTER
     * Text Description
     */
    @JsonGetter("ErrorDescription")
    public String getErrorDescription ( ) { 
        return this.errorDescription;
    }
    
    /** SETTER
     * Text Description
     */
    @JsonSetter("ErrorDescription")
    public void setErrorDescription (String value) { 
        this.errorDescription = value;
    }
 
    /** GETTER
     * a UUID Returned for the Transaction
     */
    @JsonGetter("ReferenceId")
    public UUID getReferenceId ( ) { 
        return this.referenceId;
    }
    
    /** SETTER
     * a UUID Returned for the Transaction
     */
    @JsonSetter("ReferenceId")
    public void setReferenceId (UUID value) { 
        this.referenceId = value;
    }
 
    /** GETTER
     * Return of the Clients Request ID
     */
    @JsonGetter("RequestId")
    public UUID getRequestId ( ) { 
        return this.requestId;
    }
    
    /** SETTER
     * Return of the Clients Request ID
     */
    @JsonSetter("RequestId")
    public void setRequestId (UUID value) { 
        this.requestId = value;
    }
 
}
