/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class PartnerAirtimeResponseBuilder {
    //the instance to build
    private PartnerAirtimeResponse partnerAirtimeResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PartnerAirtimeResponseBuilder() {
        partnerAirtimeResponse = new PartnerAirtimeResponse();
    }

    /**
     * Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
     */
    public PartnerAirtimeResponseBuilder errorCode(int errorCode) {
        partnerAirtimeResponse.setErrorCode(errorCode);
        return this;
    }

    /**
     * Text Description
     */
    public PartnerAirtimeResponseBuilder errorDescription(String errorDescription) {
        partnerAirtimeResponse.setErrorDescription(errorDescription);
        return this;
    }

    /**
     * a UUID Returned for the Transaction
     */
    public PartnerAirtimeResponseBuilder referenceId(UUID referenceId) {
        partnerAirtimeResponse.setReferenceId(referenceId);
        return this;
    }

    /**
     * Return of the Clients Request ID
     */
    public PartnerAirtimeResponseBuilder requestId(UUID requestId) {
        partnerAirtimeResponse.setRequestId(requestId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PartnerAirtimeResponse build() {
        return partnerAirtimeResponse;
    }
}