/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PartnerAirtimeBalanceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 789842235849324398L;
    private int errorCode = 0;
    private String errorDescription = "Success.";
    private long unitBalance = 0L;
    private long limit = 0L;
    /** GETTER
     * Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
     */
    @JsonGetter("ErrorCode")
    public int getErrorCode ( ) { 
        return this.errorCode;
    }
    
    /** SETTER
     * Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
     */
    @JsonSetter("ErrorCode")
    public void setErrorCode (int value) { 
        this.errorCode = value;
    }
 
    /** GETTER
     * Text Description
     */
    @JsonGetter("ErrorDescription")
    public String getErrorDescription ( ) { 
        return this.errorDescription;
    }
    
    /** SETTER
     * Text Description
     */
    @JsonSetter("ErrorDescription")
    public void setErrorDescription (String value) { 
        this.errorDescription = value;
    }
 
    /** GETTER
     * Remaining Tentative Balance
     */
    @JsonGetter("UnitBalance")
    public long getUnitBalance ( ) { 
        return this.unitBalance;
    }
    
    /** SETTER
     * Remaining Tentative Balance
     */
    @JsonSetter("UnitBalance")
    public void setUnitBalance (long value) { 
        this.unitBalance = value;
    }
 
    /** GETTER
     * Limit of Units to Use.
     */
    @JsonGetter("Limit")
    public long getLimit ( ) { 
        return this.limit;
    }
    
    /** SETTER
     * Limit of Units to Use.
     */
    @JsonSetter("Limit")
    public void setLimit (long value) { 
        this.limit = value;
    }
 
}
