/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class RegisterCallbackResponseBuilder {
    //the instance to build
    private RegisterCallbackResponse registerCallbackResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RegisterCallbackResponseBuilder() {
        registerCallbackResponse = new RegisterCallbackResponse();
    }

    public RegisterCallbackResponseBuilder errorCode(int errorCode) {
        registerCallbackResponse.setErrorCode(errorCode);
        return this;
    }

    public RegisterCallbackResponseBuilder errorDescription(String errorDescription) {
        registerCallbackResponse.setErrorDescription(errorDescription);
        return this;
    }

    public RegisterCallbackResponseBuilder registeredCallbackUrl(String registeredCallbackUrl) {
        registerCallbackResponse.setRegisteredCallbackUrl(registeredCallbackUrl);
        return this;
    }

    /**
     * Tracking RequestId
     */
    public RegisterCallbackResponseBuilder requestId(UUID requestId) {
        registerCallbackResponse.setRequestId(requestId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RegisterCallbackResponse build() {
        return registerCallbackResponse;
    }
}