/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class RegisterCallbackRequestBuilder {
    //the instance to build
    private RegisterCallbackRequest registerCallbackRequest;

    /**
     * Default constructor to initialize the instance
     */
    public RegisterCallbackRequestBuilder() {
        registerCallbackRequest = new RegisterCallbackRequest();
    }

    /**
     * Define a reachable URL that accepts a JSON Payload as described below
     */
    public RegisterCallbackRequestBuilder url(String url) {
        registerCallbackRequest.setUrl(url);
        return this;
    }

    /**
     * Define the transactions per second we should use when pushing callbacks to your side
     */
    public RegisterCallbackRequestBuilder tps(String tps) {
        registerCallbackRequest.setTps(tps);
        return this;
    }

    /**
     * A comma separated value, containing the number of seconds to wait for any retries and the max number of retries to do, when the clients endpoint responds with an Error
     */
    public RegisterCallbackRequestBuilder retries(String retries) {
        registerCallbackRequest.setRetries(retries);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RegisterCallbackRequest build() {
        return registerCallbackRequest;
    }
}