/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class SingleAirtimeParameter 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1825590532512026674L;
    private UUID referenceId;
    private String country = "KE";
    private String accountNo = "254705126329";
    private Denomination denomination;
    private Object other;
    /** GETTER
     * A UUID for Each
     */
    @JsonGetter("reference_id")
    public UUID getReferenceId ( ) { 
        return this.referenceId;
    }
    
    /** SETTER
     * A UUID for Each
     */
    @JsonSetter("reference_id")
    public void setReferenceId (UUID value) { 
        this.referenceId = value;
    }
 
    /** GETTER
     * Which Country are you requesting in
     */
    @JsonGetter("country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * Which Country are you requesting in
     */
    @JsonSetter("country")
    public void setCountry (String value) { 
        this.country = value;
    }
 
    /** GETTER
     * The Receipient's Account. Can be Phone Number(International Format)
     */
    @JsonGetter("account_no")
    public String getAccountNo ( ) { 
        return this.accountNo;
    }
    
    /** SETTER
     * The Receipient's Account. Can be Phone Number(International Format)
     */
    @JsonSetter("account_no")
    public void setAccountNo (String value) { 
        this.accountNo = value;
    }
 
    /** GETTER
     * Currency Declarative Type
     */
    @JsonGetter("denomination")
    public Denomination getDenomination ( ) { 
        return this.denomination;
    }
    
    /** SETTER
     * Currency Declarative Type
     */
    @JsonSetter("denomination")
    public void setDenomination (Denomination value) { 
        this.denomination = value;
    }
 
    /** GETTER
     * Any Other Tags to accompany the Request
     */
    @JsonGetter("other")
    public Object getOther ( ) { 
        return this.other;
    }
    
    /** SETTER
     * Any Other Tags to accompany the Request
     */
    @JsonSetter("other")
    public void setOther (Object value) { 
        this.other = value;
    }
 
}
