/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.credofaster.partner.apitest.models;

import java.util.*;

public class SingleAirtimeParameterBuilder {
    //the instance to build
    private SingleAirtimeParameter singleAirtimeParameter;

    /**
     * Default constructor to initialize the instance
     */
    public SingleAirtimeParameterBuilder() {
        singleAirtimeParameter = new SingleAirtimeParameter();
    }

    /**
     * A UUID for Each
     */
    public SingleAirtimeParameterBuilder referenceId(UUID referenceId) {
        singleAirtimeParameter.setReferenceId(referenceId);
        return this;
    }

    /**
     * Which Country are you requesting in
     */
    public SingleAirtimeParameterBuilder country(String country) {
        singleAirtimeParameter.setCountry(country);
        return this;
    }

    /**
     * The Receipient's Account. Can be Phone Number(International Format)
     */
    public SingleAirtimeParameterBuilder accountNo(String accountNo) {
        singleAirtimeParameter.setAccountNo(accountNo);
        return this;
    }

    /**
     * Currency Declarative Type
     */
    public SingleAirtimeParameterBuilder denomination(Denomination denomination) {
        singleAirtimeParameter.setDenomination(denomination);
        return this;
    }

    /**
     * Any Other Tags to accompany the Request
     */
    public SingleAirtimeParameterBuilder other(Object other) {
        singleAirtimeParameter.setOther(other);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SingleAirtimeParameter build() {
        return singleAirtimeParameter;
    }
}